# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC04PengajuanSuratMagang():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC04PengajuanSuratMagang(self):
    # Test name: TC_04_PengajuanSuratMagang
    # Step # | name | target | value
    # 1 | open | https://pelayanan.kesbangpol.bandung.go.id/ | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 4 | click | css=a:nth-child(3) .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) .chakra-text").click()
    # 5 | runScript | window.scrollTo(0,401.6000061035156) | 
    self.driver.execute_script("window.scrollTo(0,401.6000061035156)")
    # 6 | click | id=nama | 
    self.driver.find_element(By.ID, "nama").click()
    # 7 | type | id=nama | SUTARNO, S.S.T., M.T.
    self.driver.find_element(By.ID, "nama").send_keys("SUTARNO, S.S.T., M.T.")
    # 8 | click | id=alamat | 
    self.driver.find_element(By.ID, "alamat").click()
    # 9 | type | id=alamat | Jl. Bandara Manasaja No. 01 RT. 002/003, Kel. Rumbai, Kec. Surabaya Kota Bandung
    self.driver.find_element(By.ID, "alamat").send_keys("Jl. Bandara Manasaja No. 01 RT. 002/003, Kel. Rumbai, Kec. Surabaya Kota Bandung")
    # 10 | click | id=jenis_no_identitas | 
    self.driver.find_element(By.ID, "jenis_no_identitas").click()
    # 11 | select | id=jenis_no_identitas | label=NPM
    dropdown = self.driver.find_element(By.ID, "jenis_no_identitas")
    dropdown.find_element(By.XPATH, "//option[. = 'NPM']").click()
    # 12 | click | css=.chakra-form-control:nth-child(16) | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-form-control:nth-child(16)").click()
    # 13 | click | id=no_identitas | 
    self.driver.find_element(By.ID, "no_identitas").click()
    # 14 | type | id=no_identitas | 14765677889099
    self.driver.find_element(By.ID, "no_identitas").send_keys("14765677889099")
    # 15 | click | id=anggota | 
    self.driver.find_element(By.ID, "anggota").click()
    # 16 | type | id=anggota | Budiantono, Dianamanik
    self.driver.find_element(By.ID, "anggota").send_keys("Budiantono, Dianamanik")
    # 17 | click | id=jabatan | 
    self.driver.find_element(By.ID, "jabatan").click()
    # 18 | select | id=jabatan | label=Koordinator
    dropdown = self.driver.find_element(By.ID, "jabatan")
    dropdown.find_element(By.XPATH, "//option[. = 'Koordinator']").click()
    # 19 | click | id=nama_kampus | 
    self.driver.find_element(By.ID, "nama_kampus").click()
    # 20 | type | id=nama_kampus | Universitas Bandung
    self.driver.find_element(By.ID, "nama_kampus").send_keys("Universitas Bandung")
    # 21 | click | id=no_surat_kampus | 
    self.driver.find_element(By.ID, "no_surat_kampus").click()
    # 22 | type | id=no_surat_kampus | 0018999
    self.driver.find_element(By.ID, "no_surat_kampus").send_keys("0018999")
    # 23 | click | id=tanggal_surat_kampus | 
    self.driver.find_element(By.ID, "tanggal_surat_kampus").click()
    # 24 | type | id=tanggal_surat_kampus | 2023-09-11
    self.driver.find_element(By.ID, "tanggal_surat_kampus").send_keys("2023-09-11")
    # 25 | click | id=no_hp | 
    self.driver.find_element(By.ID, "no_hp").click()
    # 26 | type | id=no_hp | 081388789099
    self.driver.find_element(By.ID, "no_hp").send_keys("081388789099")
    # 27 | click | id=tanggal_mulai | 
    self.driver.find_element(By.ID, "tanggal_mulai").click()
    # 28 | type | id=tanggal_mulai | 2023-09-11
    self.driver.find_element(By.ID, "tanggal_mulai").send_keys("2023-09-11")
    # 29 | click | id=tanggal_akhir | 
    self.driver.find_element(By.ID, "tanggal_akhir").click()
    # 30 | type | id=tanggal_akhir | 2023-09-30
    self.driver.find_element(By.ID, "tanggal_akhir").send_keys("2023-09-30")
    # 31 | click | css=.chakra-stack:nth-child(1) > .chakra-form-control:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-stack:nth-child(1) > .chakra-form-control:nth-child(1)").click()
    # 32 | click | id=attach_ktp | 
    self.driver.find_element(By.ID, "attach_ktp").click()
    # 33 | type | id=attach_ktp | C:\fakepath\ktpdummy.png
    self.driver.find_element(By.ID, "attach_ktp").send_keys("C:\\fakepath\\ktpdummy.png")
    # 34 | click | id=attach_ktm | 
    self.driver.find_element(By.ID, "attach_ktm").click()
    # 35 | type | id=attach_ktm | C:\fakepath\ktmdummy.jpeg
    self.driver.find_element(By.ID, "attach_ktm").send_keys("C:\\fakepath\\ktmdummy.jpeg")
    # 36 | click | id=attach_pasFoto | 
    self.driver.find_element(By.ID, "attach_pasFoto").click()
    # 37 | type | id=attach_pasFoto | C:\fakepath\pasfotodummy.jpeg
    self.driver.find_element(By.ID, "attach_pasFoto").send_keys("C:\\fakepath\\pasfotodummy.jpeg")
    # 38 | click | id=attach_suratKampus | 
    self.driver.find_element(By.ID, "attach_suratKampus").click()
    # 39 | type | id=attach_suratKampus | C:\fakepath\suratkampus.jpg
    self.driver.find_element(By.ID, "attach_suratKampus").send_keys("C:\\fakepath\\suratkampus.jpg")
    # 40 | click | id=attach_vaksin | 
    self.driver.find_element(By.ID, "attach_vaksin").click()
    # 41 | type | id=attach_vaksin | C:\fakepath\vaksindummy.jpg
    self.driver.find_element(By.ID, "attach_vaksin").send_keys("C:\\fakepath\\vaksindummy.jpg")
    # 42 | click | id=attach_suratDinas | 
    self.driver.find_element(By.ID, "attach_suratDinas").click()
    # 43 | type | id=attach_suratDinas | C:\fakepath\ToDoListApp_-_Andi_Stevenli.apk
    self.driver.find_element(By.ID, "attach_suratDinas").send_keys("C:\\fakepath\\ToDoListApp_-_Andi_Stevenli.apk")
    # 44 | click | id=tombolKirim | 
    self.driver.find_element(By.ID, "tombolKirim").click()
    # 45 | click | id=berhasilHore | 
    self.driver.find_element(By.ID, "berhasilHore").click()
    # 46 | click | id=berhasilHore | 
    self.driver.find_element(By.ID, "berhasilHore").click()
  
