# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC03FooterTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_tC03FooterTest(self):
    # Test name: TC_03_FooterTest
    # Step # | name | target | value
    # 1 | open | https://pelayanan.kesbangpol.bandung.go.id/ | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | runScript | window.scrollTo(0,428.79998779296875) | 
    self.driver.execute_script("window.scrollTo(0,428.79998779296875)")
    # 4 | click | css=.css-p9pngt | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-p9pngt").click()
    # 5 | click | css=.chakra-stack:nth-child(2) > a:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-stack:nth-child(2) > a:nth-child(2)").click()
    # 6 | runScript | window.scrollTo(0,415.20001220703125) | 
    self.driver.execute_script("window.scrollTo(0,415.20001220703125)")
    # 7 | click | css=.css-1h4ws66:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1h4ws66:nth-child(2)").click()
    # 8 | click | linkText=Penelitian | 
    self.driver.find_element(By.LINK_TEXT, "Penelitian").click()
    # 9 | runScript | window.scrollTo(0,407.20001220703125) | 
    self.driver.execute_script("window.scrollTo(0,407.20001220703125)")
    # 10 | click | css=.css-1h4ws66:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1h4ws66:nth-child(2)").click()
    # 11 | click | linkText=Data/Wawancara | 
    self.driver.find_element(By.LINK_TEXT, "Data/Wawancara").click()
    # 12 | runScript | window.scrollTo(0,452.79998779296875) | 
    self.driver.execute_script("window.scrollTo(0,452.79998779296875)")
    # 13 | click | css=.css-1h4ws66:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1h4ws66:nth-child(2)").click()
    # 14 | click | linkText=PKL/Magang/KKN | 
    self.driver.find_element(By.LINK_TEXT, "PKL/Magang/KKN").click()
    # 15 | mouseOver | linkText=PKL/Magang/KKN | 
    element = self.driver.find_element(By.LINK_TEXT, "PKL/Magang/KKN")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 16 | mouseOut | linkText=PKL/Magang/KKN | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 17 | runScript | window.scrollTo(0,438.3999938964844) | 
    self.driver.execute_script("window.scrollTo(0,438.3999938964844)")
    # 18 | click | css=.css-1h4ws66:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1h4ws66:nth-child(2)").click()
    # 19 | click | css=a:nth-child(6) | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6)").click()
    # 20 | click | css=.css-1h4ws66:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1h4ws66:nth-child(2)").click()
    # 21 | click | css=.chakra-link:nth-child(2) > .chakra-button | 
    self.vars["window_handles"] = self.driver.window_handles
    # 22 | storeWindowHandle | root | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-link:nth-child(2) > .chakra-button").click()
    # 23 | selectWindow | handle=${win1271} | 
    self.vars["win1271"] = self.wait_for_window(2000)
    # 24 | close |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 25 | selectWindow | handle=${root} | 
    self.driver.switch_to.window(self.vars["win1271"])
    # 26 | click | css=.chakra-link:nth-child(3) > .chakra-button | 
    self.driver.close()
    # 27 | selectWindow | handle=${win3466} | 
    self.driver.switch_to.window(self.vars["root"])
    # 28 | close |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 29 | selectWindow | handle=${root} | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-link:nth-child(3) > .chakra-button").click()
    # 30 | click | css=.css-hyb7bs:nth-child(1) path | 
    self.vars["win3466"] = self.wait_for_window(2000)
    # 31 | executeScript | window.history.back() | 
    self.driver.switch_to.window(self.vars["win3466"])
    # 32 | pause | 5000 | 
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".css-hyb7bs:nth-child(1) path").click()
    time.sleep(5)
  
#coba