# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC01NavbarTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC01NavbarTest(self):
    # Test name: TC_01_NavbarTest
    # Step # | name | target | value
    # 1 | open | https://pelayanan.kesbangpol.bandung.go.id/ | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | id=popover-trigger-:r2: | 
    self.driver.find_element(By.ID, "popover-trigger-:r2:").click()
    # 4 | runScript | window.scrollTo(0,424.79998779296875) | 
    self.driver.execute_script("window.scrollTo(0,424.79998779296875)")
    # 5 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 6 | click | css=a:nth-child(1) > .chakra-stack .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .chakra-stack .chakra-text").click()
    # 7 | runScript | window.scrollTo(0,404.79998779296875) | 
    self.driver.execute_script("window.scrollTo(0,404.79998779296875)")
    # 8 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 9 | click | css=a:nth-child(2) .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) .chakra-text").click()
    # 10 | runScript | window.scrollTo(0,425.6000061035156) | 
    self.driver.execute_script("window.scrollTo(0,425.6000061035156)")
    # 11 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 12 | click | css=a:nth-child(3) .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) .chakra-text").click()
    # 13 | runScript | window.scrollTo(0,416.79998779296875) | 
    self.driver.execute_script("window.scrollTo(0,416.79998779296875)")
    # 14 | click | id=popover-trigger-:r6: | 
    self.driver.find_element(By.ID, "popover-trigger-:r6:").click()
    # 15 | click | css=.css-ankmtx | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-ankmtx").click()
    # 16 | click | css=.css-16h2qf1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-16h2qf1").click()
  
