# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC02PengajuanSuratPenelitian():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC02PengajuanSuratPenelitian(self):
    # Test name: TC_02_PengajuanSuratPenelitian
    # Step # | name | target | value
    # 1 | open | https://pelayanan.kesbangpol.bandung.go.id/ | 
    self.driver.get("https://pelayanan.kesbangpol.bandung.go.id/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | id=popover-trigger-:r4: | 
    self.driver.find_element(By.ID, "popover-trigger-:r4:").click()
    # 4 | click | css=a:nth-child(1) > .chakra-stack .chakra-text | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .chakra-stack .chakra-text").click()
    # 5 | runScript | window.scrollTo(0,407.20001220703125) | 
    self.driver.execute_script("window.scrollTo(0,407.20001220703125)")
    # 6 | click | id=nama | 
    self.driver.find_element(By.ID, "nama").click()
    # 7 | type | id=nama | SUTARNO, S.S.T., M.T.
    self.driver.find_element(By.ID, "nama").send_keys("SUTARNO, S.S.T., M.T.")
    # 8 | click | id=alamat | 
    self.driver.find_element(By.ID, "alamat").click()
    # 9 | type | id=alamat | Jl. Bandara Manasaja No. 01 RT. 002/003, Kel. Rumbai, Kec. Surabaya Kota Bandung
    self.driver.find_element(By.ID, "alamat").send_keys("Jl. Bandara Manasaja No. 01 RT. 002/003, Kel. Rumbai, Kec. Surabaya Kota Bandung")
    # 10 | click | id=jenis_no_identitas | 
    self.driver.find_element(By.ID, "jenis_no_identitas").click()
    # 11 | click | id=jenis_no_identitas | 
    self.driver.find_element(By.ID, "jenis_no_identitas").click()
    # 12 | click | id=jenis_no_identitas | 
    self.driver.find_element(By.ID, "jenis_no_identitas").click()
    # 13 | click | id=jenis_no_identitas | 
    self.driver.find_element(By.ID, "jenis_no_identitas").click()
    # 14 | click | css=.css-16t6c2g | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-16t6c2g").click()
    # 15 | click | id=no_identitas | 
    self.driver.find_element(By.ID, "no_identitas").click()
    # 16 | type | id=no_identitas | 14765677889099
    self.driver.find_element(By.ID, "no_identitas").send_keys("14765677889099")
    # 17 | click | id=tujuan_dinas | 
    self.driver.find_element(By.ID, "tujuan_dinas").click()
    # 18 | type | id=tujuan_dinas | Badan Kesatuan Pasar Raya
    self.driver.find_element(By.ID, "tujuan_dinas").send_keys("Badan Kesatuan Pasar Raya")
    # 19 | click | id=anggota | 
    self.driver.find_element(By.ID, "anggota").click()
    # 20 | type | id=anggota | Budiantono, Dianamanik
    self.driver.find_element(By.ID, "anggota").send_keys("Budiantono, Dianamanik")
    # 21 | click | id=jabatan | 
    self.driver.find_element(By.ID, "jabatan").click()
    # 22 | select | id=jabatan | label=Penanggung Jawab
    dropdown = self.driver.find_element(By.ID, "jabatan")
    dropdown.find_element(By.XPATH, "//option[. = 'Penanggung Jawab']").click()
    # 23 | click | css=.chakra-form-control:nth-child(19) | 
    self.driver.find_element(By.CSS_SELECTOR, ".chakra-form-control:nth-child(19)").click()
    # 24 | click | id=nama_kampus | 
    self.driver.find_element(By.ID, "nama_kampus").click()
    # 25 | type | id=nama_kampus | Universitas Bandung
    self.driver.find_element(By.ID, "nama_kampus").send_keys("Universitas Bandung")
    # 26 | click | id=no_surat_kampus | 
    self.driver.find_element(By.ID, "no_surat_kampus").click()
    # 27 | type | id=no_surat_kampus | 0018999
    self.driver.find_element(By.ID, "no_surat_kampus").send_keys("0018999")
    # 28 | click | id=tanggal_surat_kampus | 
    self.driver.find_element(By.ID, "tanggal_surat_kampus").click()
    # 29 | click | id=tanggal_surat_kampus | 
    self.driver.find_element(By.ID, "tanggal_surat_kampus").click()
    # 30 | type | id=tanggal_surat_kampus | 2023-09-11
    self.driver.find_element(By.ID, "tanggal_surat_kampus").send_keys("2023-09-11")
    # 31 | click | id=judul_penelitian | 
    self.driver.find_element(By.ID, "judul_penelitian").click()
    # 32 | type | id=judul_penelitian | Penelitian di Badan Kesatuan Pasar Raya
    self.driver.find_element(By.ID, "judul_penelitian").send_keys("Penelitian di Badan Kesatuan Pasar Raya")
    # 33 | click | id=no_hp | 
    self.driver.find_element(By.ID, "no_hp").click()
    # 34 | type | id=no_hp | 081388789099
    self.driver.find_element(By.ID, "no_hp").send_keys("081388789099")
    # 35 | click | id=attach_ktp | 
    self.driver.find_element(By.ID, "attach_ktp").click()
    # 36 | type | id=attach_ktp | C:\fakepath\ktpdummy.png
    self.driver.find_element(By.ID, "attach_ktp").send_keys("C:\\fakepath\\ktpdummy.png")
    # 37 | click | id=attach_ktm | 
    self.driver.find_element(By.ID, "attach_ktm").click()
    # 38 | type | id=attach_ktm | C:\fakepath\ktmdummy.jpeg
    self.driver.find_element(By.ID, "attach_ktm").send_keys("C:\\fakepath\\ktmdummy.jpeg")
    # 39 | click | id=attach_pasFoto | 
    self.driver.find_element(By.ID, "attach_pasFoto").click()
    # 40 | type | id=attach_pasFoto | C:\fakepath\pasfotodummy.jpeg
    self.driver.find_element(By.ID, "attach_pasFoto").send_keys("C:\\fakepath\\pasfotodummy.jpeg")
    # 41 | click | id=attach_notaris | 
    self.driver.find_element(By.ID, "attach_notaris").click()
    # 42 | type | id=attach_notaris | C:\fakepath\aktanotarisdummy.jpg
    self.driver.find_element(By.ID, "attach_notaris").send_keys("C:\\fakepath\\aktanotarisdummy.jpg")
    # 43 | click | id=attach_suratKampus | 
    self.driver.find_element(By.ID, "attach_suratKampus").click()
    # 44 | type | id=attach_suratKampus | C:\fakepath\suratkampus.jpg
    self.driver.find_element(By.ID, "attach_suratKampus").send_keys("C:\\fakepath\\suratkampus.jpg")
    # 45 | click | id=attach_vaksin | 
    self.driver.find_element(By.ID, "attach_vaksin").click()
    # 46 | type | id=attach_vaksin | C:\fakepath\vaksindummy.jpg
    self.driver.find_element(By.ID, "attach_vaksin").send_keys("C:\\fakepath\\vaksindummy.jpg")
    # 47 | click | id=attach_proposal | 
    self.driver.find_element(By.ID, "attach_proposal").click()
    # 48 | type | id=attach_proposal | C:\fakepath\PROPOSAL_FUTSAL.pdf
    self.driver.find_element(By.ID, "attach_proposal").send_keys("C:\\fakepath\\PROPOSAL_FUTSAL.pdf")
    # 49 | click | id=attach_proposal | 
    self.driver.find_element(By.ID, "attach_proposal").click()
    # 50 | type | id=attach_proposal | C:\fakepath\UAS METOPEL.pdf
    self.driver.find_element(By.ID, "attach_proposal").send_keys("C:\\fakepath\\UAS METOPEL.pdf")
    # 51 | click | id=tombolKirim | 
    self.driver.find_element(By.ID, "tombolKirim").click()
  
